// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6St91lF87rTSnKxIABTrzTY_J7ZRqmoQ',
    appId: '1:733594523005:web:8cddedff3fbe5f8f622814',
    messagingSenderId: '733594523005',
    projectId: 'agriculture-b6a3a',
    authDomain: 'agriculture-b6a3a.firebaseapp.com',
    storageBucket: 'agriculture-b6a3a.appspot.com',
    measurementId: 'G-B741596LZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBle8aAeizSVxveXw2UTtYIWQuY3G6M59I',
    appId: '1:733594523005:android:83ce98339cdfbafa622814',
    messagingSenderId: '733594523005',
    projectId: 'agriculture-b6a3a',
    storageBucket: 'agriculture-b6a3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg2DXYaNmsQ3E13QA2PtUoAW-G9b_K_Zk',
    appId: '1:733594523005:ios:e6ec78884272fbc3622814',
    messagingSenderId: '733594523005',
    projectId: 'agriculture-b6a3a',
    storageBucket: 'agriculture-b6a3a.appspot.com',
    iosBundleId: 'com.agriculture.agricol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg2DXYaNmsQ3E13QA2PtUoAW-G9b_K_Zk',
    appId: '1:733594523005:ios:e6ec78884272fbc3622814',
    messagingSenderId: '733594523005',
    projectId: 'agriculture-b6a3a',
    storageBucket: 'agriculture-b6a3a.appspot.com',
    iosBundleId: 'com.agriculture.agricol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6St91lF87rTSnKxIABTrzTY_J7ZRqmoQ',
    appId: '1:733594523005:web:efeb423b8ebab5cc622814',
    messagingSenderId: '733594523005',
    projectId: 'agriculture-b6a3a',
    authDomain: 'agriculture-b6a3a.firebaseapp.com',
    storageBucket: 'agriculture-b6a3a.appspot.com',
    measurementId: 'G-E31ZZQDZYZ',
  );
}
